# Generated by Django 4.2.7 on 2025-10-15 19:58

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('GUNLUK', 'Günlük Rapor'), ('HAFTALIK', 'Haftalık Rapor'), ('AYLIK', 'Aylık Rapor'), ('YILLIK', 'Yıllık Rapor')], max_length=20, verbose_name='Rapor Tipi')),
                ('start_date', models.DateField(verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateField(verbose_name='Bitiş Tarihi')),
                ('statistics', models.JSONField(default=dict, verbose_name='İstatistikler')),
                ('report_file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/', verbose_name='Rapor Dosyası (PDF)')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Satış Raporu',
                'verbose_name_plural': 'Satış Raporları',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Kaparo Bedeli (TL)')),
                ('deposit_payment_method', models.CharField(choices=[('NAKIT', 'Nakit'), ('KREDI_KARTI', 'Kredi Kartı'), ('DEKONT', 'Banka Havalesi/Dekont'), ('CEK', 'Çek')], max_length=20, verbose_name='Kaparo Ödeme Yöntemi')),
                ('deposit_receipt_number', models.CharField(blank=True, max_length=100, verbose_name='Kaparo Makbuz/Dekont No')),
                ('status', models.CharField(choices=[('AKTIF', 'Aktif Rezervasyon'), ('SATISA_DONUSTU', 'Satışa Dönüştü'), ('IPTAL_EDILDI', 'İptal Edildi')], default='AKTIF', max_length=20, verbose_name='Rezervasyon Durumu')),
                ('reservation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Rezervasyon Tarihi')),
                ('expiry_date', models.DateField(blank=True, help_text='Rezervasyonun geçerlilik süresi (opsiyonel)', null=True, verbose_name='Son Geçerlilik Tarihi')),
                ('notes', models.TextField(blank=True, verbose_name='Rezervasyon Notları')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reservations', to=settings.AUTH_USER_MODEL, verbose_name='Kaydı Oluşturan')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='crm.customer', verbose_name='Müşteri')),
                ('payment_plan_selected', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='properties.paymentplan', verbose_name='Seçilen Ödeme Planı')),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reservation', to='properties.property', verbose_name='Gayrimenkul')),
                ('sales_rep', models.ForeignKey(limit_choices_to={'role': 'SATIS_TEMSILCISI'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='Satış Temsilcisi')),
            ],
            options={
                'verbose_name': 'Rezervasyon',
                'verbose_name_plural': 'Rezervasyonlar',
                'ordering': ['-reservation_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('KAPARO', 'Kaparo'), ('PESINAT', 'Peşinat'), ('TAKSIT', 'Taksit'), ('KALAN_ODEME', 'Kalan Ödeme')], max_length=20, verbose_name='Ödeme Tipi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Tutar (TL)')),
                ('payment_method', models.CharField(blank=True, choices=[('NAKIT', 'Nakit'), ('KREDI_KARTI', 'Kredi Kartı'), ('HAVALE', 'Banka Havalesi'), ('CEK', 'Çek')], max_length=20, verbose_name='Ödeme Yöntemi')),
                ('status', models.CharField(choices=[('BEKLENIYOR', 'Ödeme Bekleniyor'), ('ALINDI', 'Ödeme Alındı'), ('GECIKTI', 'Ödeme Gecikti'), ('IPTAL', 'İptal Edildi')], default='BEKLENIYOR', max_length=20, verbose_name='Durum')),
                ('due_date', models.DateField(verbose_name='Vade Tarihi')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Ödeme Tarihi')),
                ('receipt_number', models.CharField(blank=True, max_length=100, verbose_name='Makbuz/Dekont No')),
                ('installment_number', models.PositiveIntegerField(blank=True, help_text='Taksit ödemesi ise kaçıncı taksit', null=True, verbose_name='Taksit Numarası')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL, verbose_name='Kaydeden')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.reservation', verbose_name='Rezervasyon')),
            ],
            options={
                'verbose_name': 'Ödeme',
                'verbose_name_plural': 'Ödemeler',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('REZERVASYON', 'Rezervasyon Sözleşmesi'), ('SATIS', 'Satış Sözleşmesi'), ('ON_SOZLESME', 'Ön Sözleşme')], default='REZERVASYON', max_length=20, verbose_name='Sözleşme Tipi')),
                ('contract_number', models.CharField(max_length=50, unique=True, verbose_name='Sözleşme No')),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='contracts/%Y/%m/', verbose_name='Sözleşme Dosyası (PDF)')),
                ('status', models.CharField(choices=[('TASLAK', 'Taslak'), ('ONAY_BEKLIYOR', 'Onay Bekliyor'), ('IMZALANDI', 'İmzalandı'), ('IPTAL', 'İptal Edildi')], default='TASLAK', max_length=20, verbose_name='Durum')),
                ('contract_date', models.DateField(default=django.utils.timezone.now, verbose_name='Sözleşme Tarihi')),
                ('signed_date', models.DateField(blank=True, null=True, verbose_name='İmza Tarihi')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='sales.reservation', verbose_name='Rezervasyon')),
            ],
            options={
                'verbose_name': 'Sözleşme',
                'verbose_name_plural': 'Sözleşmeler',
                'ordering': ['-contract_date'],
            },
        ),
    ]
