# Generated by Django 4.2.7 on 2025-10-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreport',
            name='report_type',
            field=models.CharField(choices=[('GENEL_Ozet', 'Genel Satış Özeti'), ('TEMSILCI_PERFORMANS', 'Temsilci Performans Raporu'), ('MUSTERI_KAYNAK', 'Müşteri Kaynak Raporu'), ('GUNLUK', 'Günlük Rapor'), ('HAFTALIK', 'Haftalık Rapor'), ('AYLIK', 'Aylık Rapor'), ('YILLIK', 'Yıllık Rapor')], max_length=30, verbose_name='Rapor Tipi'),
        ),
    ]
