# Generated by Django 4.2.7 on 2025-10-15 19:57

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255, verbose_name='Proje Adı')),
                ('island', models.CharField(blank=True, max_length=50, verbose_name='Ada')),
                ('parcel', models.CharField(blank=True, max_length=50, verbose_name='Pafta')),
                ('block', models.CharField(max_length=50, verbose_name='Blok')),
                ('floor', models.IntegerField(validators=[django.core.validators.MinValueValidator(-5)], verbose_name='Kat')),
                ('unit_number', models.CharField(max_length=20, verbose_name='Bağımsız Bölüm No')),
                ('facade', models.CharField(choices=[('GUNEY', 'Güney'), ('KUZEY', 'Kuzey'), ('DOGU', 'Doğu'), ('BATI', 'Batı'), ('GUNEY_DOGU', 'Güney-Doğu'), ('GUNEY_BATI', 'Güney-Batı'), ('KUZEY_DOGU', 'Kuzey-Doğu'), ('KUZEY_BATI', 'Kuzey-Batı')], max_length=20, verbose_name='Cephe')),
                ('property_type', models.CharField(choices=[('DAIRE', 'Daire'), ('VILLA', 'Villa'), ('OFIS', 'Ofis')], default='DAIRE', max_length=10, verbose_name='Mülk Tipi')),
                ('room_count', models.CharField(help_text='Örn: 1+1, 2+1, 3+1 Dubleks', max_length=50, verbose_name='Oda Sayısı')),
                ('gross_area_m2', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Brüt Alan (m²)')),
                ('net_area_m2', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Net Alan (m²)')),
                ('cash_price', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Peşin Fiyat (TL)')),
                ('installment_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Vadeli Fiyat (TL)')),
                ('status', models.CharField(choices=[('SATILABILIR', 'Satılabilir'), ('REZERVE', 'Rezerve'), ('SATILDI', 'Satıldı'), ('PASIF', 'Pasif')], default='SATILABILIR', max_length=15, verbose_name='Durum')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_properties', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Gayrimenkul',
                'verbose_name_plural': 'Gayrimenkuller',
                'ordering': ['project_name', 'block', 'floor', 'unit_number'],
                'unique_together': {('project_name', 'block', 'floor', 'unit_number')},
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/images/%Y/%m/', verbose_name='Görsel')),
                ('image_type', models.CharField(choices=[('EXTERIOR', 'Dış Görünüm'), ('INTERIOR', 'İç Görünüm'), ('FLOOR_PLAN', 'Kat Planı'), ('SITE_PLAN', 'Vaziyet Planı')], default='INTERIOR', max_length=20, verbose_name='Görsel Tipi')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Başlık')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Yüklenme Tarihi')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property', verbose_name='Gayrimenkul')),
            ],
            options={
                'verbose_name': 'Gayrimenkul Görseli',
                'verbose_name_plural': 'Gayrimenkul Görselleri',
                'ordering': ['property', 'order'],
            },
        ),
        migrations.CreateModel(
            name='PropertyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='properties/documents/%Y/%m/', verbose_name='Belge')),
                ('document_type', models.CharField(choices=[('RUHSAT', 'İnşaat Ruhsatı'), ('TAPU', 'Tapu'), ('ISKAN', 'İskan Belgesi'), ('KAT_IRTIFAKI', 'Kat İrtifakı'), ('DIGER', 'Diğer')], max_length=20, verbose_name='Belge Tipi')),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Yüklenme Tarihi')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='properties.property', verbose_name='Gayrimenkul')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yükleyen')),
            ],
            options={
                'verbose_name': 'Gayrimenkul Belgesi',
                'verbose_name_plural': 'Gayrimenkul Belgeleri',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('PESIN', 'Peşin'), ('VADELI', 'Vadeli')], max_length=10, verbose_name='Plan Tipi')),
                ('name', models.CharField(help_text='Örn: %25 Peşin, 120 Ay Vade', max_length=255, verbose_name='Plan Adı')),
                ('details', models.JSONField(default=dict, help_text='Peşinat, taksit sayısı, aylık taksit vb.', verbose_name='Plan Detayları')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_plans', to='properties.property', verbose_name='Gayrimenkul')),
            ],
            options={
                'verbose_name': 'Ödeme Planı',
                'verbose_name_plural': 'Ödeme Planları',
                'ordering': ['-created_at'],
            },
        ),
    ]
