# Generated by Django 4.2.7 on 2025-10-19 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_finalize_project_schema'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['project', 'block', 'floor', 'unit_number'], 'verbose_name': 'Gayrimenkul', 'verbose_name_plural': 'Gayrimenkuller'},
        ),
        migrations.AlterField(
            model_name='property',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='properties.project', verbose_name='Proje'),
        ),
    ]
