# Generated by Django 4.2.7 on 2025-10-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_property_options_alter_property_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='island',
        ),
        migrations.RemoveField(
            model_name='property',
            name='parcel',
        ),
        migrations.AddField(
            model_name='project',
            name='block',
            field=models.CharField(blank=True, help_text='Proje tek blok ise burayı doldurun.', max_length=50, null=True, verbose_name='Blok (Genel)'),
        ),
        migrations.AddField(
            model_name='project',
            name='island',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ada'),
        ),
        migrations.AddField(
            model_name='project',
            name='parcel',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pafta'),
        ),
        migrations.AlterField(
            model_name='property',
            name='block',
            field=models.CharField(blank=True, help_text='Projede birden fazla blok varsa burayı doldurun.', max_length=50, verbose_name='Blok'),
        ),
    ]
