# Generated by Django 4.2.7 on 2025-10-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_remove_property_island_remove_property_parcel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/images/', verbose_name='Proje Görseli'),
        ),
        migrations.AddField(
            model_name='project',
            name='site_plan_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/site_plans/', verbose_name='Proje Vaziyet Planı'),
        ),
    ]
