# Generated by Django 4.2.7 on 2025-10-15 19:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Ad Soyad')),
                ('phone_number', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Telefon numarası '+999999999' formatında olmalıdır.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefon Numarası')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-posta')),
                ('source', models.CharField(choices=[('REFERANS', 'Referans'), ('WEB_SITESI', 'Web Sitesi'), ('SOSYAL_MEDYA', 'Sosyal Medya'), ('TABELA', 'Tabela'), ('OFIS_ZIYARETI', 'Ofis Ziyareti'), ('FUAR', 'Fuar'), ('DIGER', 'Diğer')], default='DIGER', max_length=20, verbose_name='Müşteri Kaynağı')),
                ('interested_in', models.CharField(blank=True, help_text='Örn: 2+1, 3+1', max_length=255, verbose_name='İlgilendiği Daire Tipleri')),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Minimum Bütçe (TL)')),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Maksimum Bütçe (TL)')),
                ('notes', models.TextField(blank=True, verbose_name='Genel Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('assigned_to', models.ForeignKey(limit_choices_to={'role': 'SATIS_TEMSILCISI'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_customers', to=settings.AUTH_USER_MODEL, verbose_name='Atandığı Satış Temsilcisi')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customers', to=settings.AUTH_USER_MODEL, verbose_name='Kaydı Oluşturan')),
            ],
            options={
                'verbose_name': 'Müşteri',
                'verbose_name_plural': 'Müşteriler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Not İçeriği')),
                ('is_important', models.BooleanField(default=False, verbose_name='Önemli Not')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_notes', to='crm.customer', verbose_name='Müşteri')),
            ],
            options={
                'verbose_name': 'Not',
                'verbose_name_plural': 'Notlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField(verbose_name='Randevu Tarihi ve Saati')),
                ('location', models.CharField(blank=True, help_text='Örn: Satış Ofisi, Şantiye', max_length=255, verbose_name='Randevu Yeri')),
                ('status', models.CharField(choices=[('PLANLANDI', 'Planlandı'), ('TAMAMLANDI', 'Tamamlandı'), ('IPTAL_EDILDI', 'İptal Edildi'), ('GELMEDI', 'Gelmedi')], default='PLANLANDI', max_length=20, verbose_name='Durum')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='Hatırlatma Gönderildi mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='crm.customer', verbose_name='Müşteri')),
                ('sales_rep', models.ForeignKey(limit_choices_to={'role': 'SATIS_TEMSILCISI'}, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='Satış Temsilcisi')),
            ],
            options={
                'verbose_name': 'Randevu',
                'verbose_name_plural': 'Randevular',
                'ordering': ['appointment_date'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('GORUSME', 'Yüz Yüze Görüşme'), ('TELEFON', 'Telefon Görüşmesi'), ('EMAIL', 'E-posta'), ('RANDEVU', 'Randevu'), ('WHATSAPP', 'WhatsApp')], max_length=20, verbose_name='Aktivite Tipi')),
                ('notes', models.TextField(verbose_name='Görüşme Notları')),
                ('outcome_score', models.IntegerField(choices=[(10, '%10 - Düşük İlgi'), (25, '%25 - Az İlgili'), (50, '%50 - Orta Düzey İlgi'), (75, '%75 - Yüksek İlgi'), (100, '%100 - Çok Yakın')], default=50, verbose_name='Kazanma Olasılığı')),
                ('next_follow_up_date', models.DateTimeField(blank=True, null=True, verbose_name='Sonraki Takip Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_activities', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.customer', verbose_name='Müşteri')),
            ],
            options={
                'verbose_name': 'Aktivite',
                'verbose_name_plural': 'Aktiviteler',
                'ordering': ['-created_at'],
            },
        ),
    ]
