# Generated by Django 4.2.7 on 2025-10-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='sub_type',
            field=models.CharField(blank=True, choices=[('ILK_GELEN', 'İlk Gelen'), ('ARA_GELEN', 'Ara Gelen')], help_text='Aktivitenin alt kategorisi (örn: İlk Gelen, Ara Gelen)', max_length=20, null=True, verbose_name='Alt Tür'),
        ),
    ]
